import { Navbar } from "@/components/Navbar";
import { Button } from "@mantine/core";
import { signOut, useSession } from "next-auth/react";
import Head from "next/head";
export default function Home() {
  const { data: session } = useSession({
    required: true,
  });

  if (!session) {
    return <></>;
  }

  return (
    <>
      <Head>
        <title>Nilam Finance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Button color={"red"} onClick={() => signOut()}>
        SignOut
      </Button>
    </>
  );
}
