import Dashboard from "@/components/Dashboard";
import { Navbar } from "@/components/Navbar";
import { LoadingOverlay } from "@mantine/core";
import { useDisclosure } from "@mantine/hooks";
import axios from "axios";
import Head from "next/head";
import { useEffect, useState } from "react";
export default function Home() {
  const [data, setData] = useState([])
  
  const [visible, { toggle }] = useDisclosure(true);
  useEffect(()=>{    
    const getData = async () => {
      const res = await axios.get("http://localhost:3000/api/getAll");
      setData(res.data.data)
      toggle();
    }
    getData();
  },[])
  return (
    <>
      <Head>
        <title>Nilam Finances</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />      
      <LoadingOverlay visible={visible} overlayBlur={2} />
      <Dashboard data={data} />
    </>
  );
}
